name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # CONSTRUYO
    # 1. Clono el repositorio
    - name: Checkout repository
      uses: actions/checkout@v4

     # 2. Configuro Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      # Uso v3 porque es la misma del checkout
      # BuildX sirve para construir imágenes de Docker

      # 3. Levantar docker con docker-compose
    - name: Start Docker services
      run: docker compose up -d --build
      # Construye las imágenes de Docker basándose en el docker-compose
      # -d para hacerlo en segundo plano
      # Resultado del paso: Los contenedores quedan listos para correr las acciones

    # EMPIEZA EL PROCESO
    # Trato backend y frontend por separado

    # 4. Backend - Ejecutar tests
    - name: Run backend tests
      run: docker compose exec backend npm test
      # Ejecuta los tests que tengo en backend/test
      # docker exec es para correr un comando dentro del contenedor ya levantado -> deli-lunch-backend
    
    
      # 5. Frontend - Verificar que está corriendo
    - name: Verify frontend is running
      run: docker compose exec frontend npm list react
      # Verifico que React esté instalado y el contenedor funcione

    # 6. Verificar que los servicios estén corriendo correctamente
    - name: Check running services
      run: docker compose ps
      # Verifico que ambos contenedores estén corriendo

    - name: Test backend connectivity
      run: docker compose exec backend node -e "console.log('Backend container is working')"
      # Verifico que el contenedor backend responde usando node

    - name: Test frontend connectivity  
      run: docker compose exec frontend node -e "console.log('Frontend container is working')"
      # Verifico que el contenedor frontend responde usando node


      # 7. Apagar los servicios del docker
    - name: Stop Docker services
      run: docker compose down
      # Apago y limpio los contenedores levantados
