name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # CONSTRUYO
    # 1. Clono el repositorio
    - name: Checkout repository
      uses: actions/checkout@v4

     # 2. Configuro Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      # Uso v3 porque es la misma del checkout
      # BuildX sirve para construir imágenes de Docker

      # 3. Levantar docker con docker-compose
    - name: Start Docker services
      run: docker-compose up -d --build
      # Construye las imágenes de Docker basándose en el docker-compose
      # -d para hacerlo en segundo plano
      # Resultado del paso: Los contenedores quedan listos para correr las acciones

    # EMPIEZA EL PROCESO
    # Trato backend y frontend por separado

    # 4. Backend - Ejecutar tests
    - name: Run backend tests
      run: docker exec deli-lunch-backend npm test
      # Ejecuta los tests que tengo en backend/test
      # docker exec es para correr un comando dentro del contenedor ya levantado -> deli-lunch-backend

     # 5. Frontend - Build y test
    - name: Build frontend
      run: docker exec deli-lunch-frontend npm run build
      # Genero el build del front dentro del contenedor

      # 6. Apagar los servicios del docker
    - name: Stop Docker services
      run: docker-compose down
      # Apago y limpio los contenedores levantados
